export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const PROGRAM_LOADING = 'PROGRAM_LOADING';
export const GET_COURSE = 'GET_COURSE';
export const GET_COURSES = 'GET_COURSES';
export const CLEAR_CURRENT_COURSE = 'CLEAR_CURRENT_COURSE';